language: java
jdk:
  - oraclejdk8
before_script:
  - export SPARK_HOME="$HOME/spark/spark_home"
  - export SPARK_JAR=$SPARK_HOME/lib/spark-assembly.jar
  - chmod 777 ./setup_test_env.sh
  - ./setup_test_env.sh
script:
  mvn clean verify
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 1a6f1b96-14e9-4dbe-b250-316a4ea3795f
cache:
  - $SPARK_HOME
  - $SPARK_JAR